### PR TITLE
Implement focuser motion in separate thread to make it interruptable.

### PR DESCRIPTION
**Pull request by picciux**
Hi,

this is my first try at implementing background/interruptible focuser motion in astroberry_focuser. 
Basically:
 - prepare data for the bg thread: put related properties values (backlash, step delay, etc) in fields used esclusively by the bg thread
 - start thread with actual gpio banging
 - periodically check status (running, position) in TimerHit, using some atomics shared with bg thread, and updating props (AbsPosition,...).
 - Do final props update and other housekeeping (save position, log, etc) when bg thread completed its work (or it's aborted).

For you to review and merge if appropriate.

Regards
Matteo

### CODE REVIEW

**Comment by rkaczorek** [comment]
Thanks for the PR. I will review it and let you know. Have you tested it before submitting for review?

**Comment by picciux** [comment]
Yes I have. 
But today I found a bug that happens when standby timer (set at last motion completion but not fired yet) triggers while focuser is moving. Fix is trivial: standby timer needs to be canceled in MoveAbsFocuser. Here is relevant diff:

```
diff --git a/astroberry_focuser.cpp b/astroberry_focuser.cpp
index c849967..e4c50cc 100644
--- a/astroberry_focuser.cpp
+++ b/astroberry_focuser.cpp
@@ -953,6 +953,10 @@ IPState AstroberryFocuser::MoveAbsFocuser(int targetTicks)
        FocusAbsPosNP.s = IPS_BUSY;
        IDSetNumber(&FocusAbsPosNP, nullptr);

+       //abort any pending Standby Timer to avoid it fires
+       //during a move.
+       IERmTimer(stepperStandbyID);
+
        // prepare data for thread to run
        threadFocuserAbs.store(FocusAbsPosN[0].value);
        threadStepDelay = FocusStepDelayN[0].value;
```

This bug made me think of another "timer-interaction": also the temperature compensation one could fire while focuser is moving; risk is "only" to miss the compensation (temperature compensation asks MoveAbsFocuser to adjust position, and MoveAbsFocuser will discart the request if focuser is moving), but obviously a better fix is needed. I'll work on it next week.

Regards

**Comment by rkaczorek** [comment]
Thanks for that. Please add this and upcoming changes to the PR

**Comment by picciux** [comment]
Hi Radek,

I reworked the code to better accomodate temperature compensation. Since temperature compensation should do its work to adjust a previously 'focused' position, it's ok if its timer doesn't fire while focuser is moving: in fact if focuser is moving we're probably 'focusing', and we'll probably need to temp-compensate later. Every time a focuser motion finishes we store current temperature, so that temperature compensation code can adjust the position when it's needed. If a focuser move is aborted, we don't store current temperature, since we're sure that was not a successful focusing operation.

**Comment by rkaczorek** [comment]
Thanks for this pull request @picciux 
I have decided to implement abort focuser function based on SetTimer/TimerHit as inspired by @jryd2000
These are INDI native background tasks so no external libraries or new dependencies are needed.
Thank you both for your support. Much appreciated

**Pull request closed without merging**
